# Introduction to Tensors

This notebook provides a beginner-friendly introduction to tensors using TensorFlow. Tensors are the fundamental data structure in many machine learning frameworks, including TensorFlow and PyTorch. They are similar to arrays or matrices, but can have more dimensions.

Let's get started by learning how to work with tensors!

In [1]:
# Import TensorFlow
import tensorflow as tf
print('TensorFlow version:', tf.__version__)

2025-09-03 21:08:52.134525: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-03 21:08:52.134925: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-03 21:08:52.137193: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-03 21:08:52.142988: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1756930132.152398    6527 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756930132.15

TensorFlow version: 2.19.0


## Creating a Basic Tensor

A tensor is a multi-dimensional array. Let's create a simple 1D and 2D tensor using TensorFlow.

In [8]:
# Create a 1D tensor (vector)
tensor_1d = tf.constant([1, 2, 3, 4])
print('1D tensor:', tensor_1d)

# Create a 2D tensor (matrix)
tensor_2d = tf.constant([[1, 2], [3, 4]])
print('2D tensor:\n', tensor_2d)

1D tensor: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
2D tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Tensor Properties and Shape

Each tensor has properties such as shape (dimensions), data type, and number of dimensions. Let's explore these properties.

In [9]:
# Display properties of the 2D tensor
print('Shape:', tensor_2d.shape)
print('Data type:', tensor_2d.dtype)
print('Number of dimensions:', tensor_2d.ndim)

Shape: (2, 2)
Data type: <dtype: 'int32'>
Number of dimensions: 2


## Basic Tensor Operations

Tensors support a variety of operations, such as addition, multiplication, and element-wise operations. Let's see some examples.

In [10]:
# Addition
add_result = tensor_2d + 2
print('Add 2 to every element:\n', add_result)

# Element-wise multiplication
mul_result = tensor_2d * 3
print('Multiply every element by 3:\n', mul_result)

# Element-wise operation with another tensor
other_tensor = tf.constant([[5, 6], [7, 8]])
sum_tensors = tensor_2d + other_tensor
print('Sum of two tensors:\n', sum_tensors)

Add 2 to every element:
 tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)
Multiply every element by 3:
 tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
Sum of two tensors:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


## Reshaping Tensors

You can change the shape of a tensor using the `reshape` method. This is useful for preparing data for machine learning models.

In [11]:
# Reshape a 1D tensor to 2D
tensor_reshaped = tf.reshape(tensor_1d, (2, 2))
print('Reshaped tensor (2x2):\n', tensor_reshaped)

Reshaped tensor (2x2):
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Indexing and Slicing Tensors

You can access specific elements or slices of a tensor using indexing, similar to lists or arrays in Python.

In [12]:
# Access the first row of the 2D tensor
print('First row:', tensor_2d[0])

# Access the element in the second row, first column
print('Element at (1, 0):', tensor_2d[1, 0])

# Slice the first column
print('First column:', tensor_2d[:, 0])

First row: tf.Tensor([1 2], shape=(2,), dtype=int32)
Element at (1, 0): tf.Tensor(3, shape=(), dtype=int32)
First column: tf.Tensor([1 3], shape=(2,), dtype=int32)


# Summary

- Tensors are multi-dimensional arrays used in machine learning frameworks like TensorFlow.
- You can create, reshape, and perform operations on tensors easily.
- Indexing and slicing allow you to access specific elements or parts of a tensor.

Explore more tensor operations as you continue your learning!